global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'expe-payment-gateway'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4001']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4002']

  - job_name: 'merchant-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4003']

  # Remove MongoDB/Redis direct scraping (no HTTP metrics without exporters)
